### ISSUE TITLE
[Bug]: `governance/contributions/issue-templates/` not found on website

### ISSUE THREAD

**Issue by pogi7** [NASA-AMMOS/slim#103]
### Checked for duplicates

Yes - I've already checked

### Website or Best Practice Guide?

Website

### Describe the bug

When I did went to this link https://nasa-ammos.github.io/slim/docs/guides/search/governance/contributions/issue-templates/ action, I noticed that there was no page that showed `issue-templates`

### What did you expect?

I expected an `issue-templates` page to show up when I clicked https://nasa-ammos.github.io/slim/docs/guides/search/governance/contributions/issue-templates/

### Reproducible steps

```bash
1.Go to https://nasa-ammos.github.io/slim/docs/guides/search/governance/contributions/issue-templates/
```

### Environment

```bash
I'm using Safari to access Github Pages to view this URL https://nasa-ammos.github.io/slim/docs/guides/search/governance/contributions/issue-templates/
```

**Comment by riverma** [comment]
Hi @pogi7 - thanks for reporting this! Looks like a discrepancy between a local build and a GitHub build may be to blame. Will investigate and fix.

For now - you can access the issue template raw files here (note the directory structure to obtain other raw templates in case this problem applies to them as well): https://github.com/NASA-AMMOS/slim/tree/main/docs/guides/governance/contributions/issue-templates/github

**Comment by riverma** [comment]
@pogi7 - could you elaborate how you originally generated the [bad link](https://nasa-ammos.github.io/slim/docs/guides/search/governance/contributions/issue-templates/) from the website? The proper link you should be sent to is [this one](https://nasa-ammos.github.io/slim/docs/guides/governance/contributions/issue-templates/).

**Comment by pogi7** [comment]
@riverma I went to https://nasa-ammos.github.io/slim/docs/guides/search and searched for `Issue` and it took me to the bad link.  When I go on the aforementioned link now and search for `issue` it takes me to the correct link.

**Comment by riverma** [comment]
@pogi7 I was able to reproduce this bug. Will investigate - thanks for the heads up!

**Comment by riverma** [comment]
It looks like the way to reproduce this error is:
1. Navigate to https://nasa-ammos.github.io/slim/docs/guides/search or refresh that page if its open
2. Click any of the panel “View” buttons
3. Receive the below error:
    ```
    Page Not Found
    We could not find what you were looking for.

    Please contact the owner of the site that linked you to the original URL and let them know their link is broken.
    ```

The strange thing is that this bug _does not appear_ when someone navigates to the search page not directly, but via the website’s relative links (i.e. [homepage](https://nasa-ammos.github.io/slim/) or via clicking the top navbar) and clicks a “View” button link. This is likely a bug in how the [FacetedPanels](https://github.com/NASA-AMMOS/slim/blob/main/src/components/FacetedPanels.js) component handles the `uri` string and how Docusaurus auto-prepends relative URIs with a base URL. Needs further investigation.

**Comment by riverma** [comment]
@pogi7 - this has been resolved. Thanks for filing a ticket!
