### ISSUE TITLE
[New Website Feature]: 301 redirects for "Detect Secrets" page

### ISSUE THREAD

**Issue by nutjob4life** [NASA-AMMOS/slim#177]
### Checked for duplicates

Yes - I've already checked

### Alternatives considered

Yes - and alternatives don't suffice

### Related problems

The [secrets detection guide](https://nasa-ammos.github.io/slim/continuous-testing/starter-kits/#detect-secrets) has a section on setting up a GitHub Action for server-side scans. The action YAML includes a reference to this URL:

    https://nasa-ammos.github.io/slim/continuous-testing/starter-kits/#detect-secrets

However, the URL is giving 404 Not Found.

### Describe the feature request

The guild should be updated of course, however, there are many repositories already using that identical YAML (~45 in PDS alone), and updating 45 separate YAML files to fix the URL would be far too onerous.

Instead, the URL above should produce a 301 permanent redirect to [the new location](https://nasa-ammos.github.io/slim/docs/guides/software-lifecycle/security/secrets-detection/). Note that the URL above includes a fragment identifier; [that might be okay](https://stackoverflow.com/questions/386709/can-you-write-a-301-redirect-to-an-anchor-point), but might also require some fanciness.

Alternatively: move the guide back to its original location 🤷

**Comment by yunks128** [comment]
@nutjob4life Thanks for your report! I was able to fix it, and here's the pull request! 
https://github.com/NASA-AMMOS/slim/pull/178

**Comment by nutjob4life** [comment]
@yunks128 you are way too fast! 🏎️ 💨 

Thanks for tackling this even on an RDO day 😊

**Comment by yunks128** [comment]
@nutjob4life My pleasure! Happy weekend!
