### ISSUE TITLE
[New Process Improvement Need]: Python base-project to integrate with GitHub Actions, PyPy, etc.

### ISSUE THREAD

**Issue by riverma** [NASA-AMMOS/slim#46]
### Checked for duplicates

Yes - I've already checked

### Category

Software Lifecycle - the creation, change, and release of software

### Describe the need

We have a need for a base Python base project, that is ready for _new projects_ to leverage GitHub Actions, PyPy, and other Python ecosystem tools.

**Comment by riverma** [comment]
Recommendation: leverage a GitHub template repo to allow a user to clone / customize a starter repo.

**Comment by jpl-jengelke** [comment]
Technical work is basically complete on this. Demo presented to SLIM.

**Comment by jpl-jengelke** [comment]
Use cases
1. New project (make it a Template repository)
2. Clone
3. Selectively apply changes

Instructions
1. Directions on how to build (compile and install as package)
2. Directions release (tag, publish release info, push to PyPi)

**Comment by jpl-jengelke** [comment]
Goal: Have a third-party run through the setup of a project using the template.

**Comment by riverma** [comment]
+1’d by @sujen1412

**Comment by jpl-jengelke** [comment]
Complete.
