### ISSUE TITLE
[New Process Improvement Need]: GitHub Org and sub-projects structure guidance

### ISSUE THREAD

**Issue by riverma** [NASA-AMMOS/slim#54]
### Checked for duplicates

Yes - I've already checked

### Category

Governance - people, personnel, organization, etc.

### Describe the need

We have a need for guidance on overall structure of GitHub Org and sub-projects. (+1'd by @kgrimes2 @mcduffie)

**Comment by Scotchester** [comment]
Dupe of #45. Looks like this one has the more correct Category, but the prior one has an additional +1 attributed to it.

**Comment by riverma** [comment]
Great catch @Scotchester! Thanks for finding the duplicate. I'll go ahead and close this ticket in place of #45. Thank you again.

**Comment by riverma** [comment]
+1'd by @ramesh-maddegoda (Unity, PDS)
