### ISSUE TITLE
[New Process Improvement Need]: Best Practices for Coding Standards to Avoid Security Issues

### ISSUE THREAD

**Issue by riverma** [NASA-AMMOS/slim#61]
### Checked for duplicates

Yes - I've already checked

### Category

Security - application, network, hardware, etc. security topics

### Describe the need

We have a need for the construction of coding standard training guides for avoiding common JPL language-dependent security weaknesses. (+1'd by @LucaCinquini @ramesh-maddegoda)

**Comment by riverma** [comment]
+1'd by @ramesh-maddegoda (Unity, PDS)

**Comment by riverma** [comment]
Hi @ramesh-maddegoda - I think this might be duplicated by another ticket that has seen some progress lately. What do you think about sharing your thoughts on the other ticket and I can close this one?
- Ticket: https://github.com/NASA-AMMOS/slim/issues/109
- Associated PR: https://github.com/NASA-AMMOS/slim/pull/116
- Best Practice Guide (from draft PR above): https://github.com/NASA-AMMOS/slim/tree/issue-109/docs/guides/software-lifecycle/security/developer-best-practices

**Comment by ramesh-maddegoda** [comment]
@riverma , Agreed. This can be covered under the ticket https://github.com/NASA-AMMOS/slim/issues/109

**Comment by ramesh-maddegoda** [comment]
Closed as this is getting covered by the following ticket. 

[New Best Practice Guide]: Security To-Do's for Devs https://github.com/NASA-AMMOS/slim/issues/109

**Comment by riverma** [comment]
Closed as not planned.
