### ISSUE TITLE
Error in Markmap Action: Failure when no changes required for commits

### ISSUE THREAD

**Issue by jpl-jengelke** [NASA-AMMOS/slim#87]
### Checked for duplicates

Yes - I've already checked

### Website or Best Practice Guide?

Website

### Describe the bug

When a release is performed, automation regenerates Markmap markup for publication to the SLIM website. When an `.md` file changes anywhere in the repository tree, the action is triggered. When no markmap-generated files change, no commit is made to the repository and the action fails. The failure is precipitated by Git not finding any files to re-commit to the repository. This is an erroneous failure.

### What did you expect?

Git should detect when there are no commits and the script should exit gracefully with a success exit code since that is performing as expected.

### Reproducible steps

```bash
1. Change a markdown file, like `CHANGELOG.md`.
2. Perform a product tag/release.
3. Check the Actions tab to see a failed markmap action.
```

### Environment

```bash
- GitHub `ubuntu-latest`
- Node 16 per recent GitHub requirements changes -- see https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
```

**Comment by riverma** [comment]
Thanks for reporting this bug @jpl-jengelke
